Remove unnecessary step to fix CI
It seems bundler is installed by travis without any setting

https://travis-ci.org/github/yuya-takeyama/flagship/jobs/678123423

```
$ gem install bundler --no-document
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.
The command "gem install bundler --no-document" failed and exited with 1 during .
```